### ISSUE TITLE
The PQ value is inconsistent

### ISSUE THREAD

**Issue by yaozhicheng** [facebookresearch/MaskFormer#12]
In MODEL_ZOO.md the PQ value in the COCO Panoptic Segment table is inconsistent with the PQ value displayed in its metric file. For example, for the "R50 plus 6 Enc" configuration, the PQ in the table is [46.5](https://github.com/facebookresearch/MaskFormer/blob/master/MODEL_ZOO.md#panoptic-segmentation-models), but [40.5](https://dl.fbaipublicfiles.com/maskformer/panoptic-coco/maskformer_panoptic_R50_bs64_554k/metrics.json) in the metric file. For "Swin-L" configuration, however, the PQ values in both the table and the [metric file](https://dl.fbaipublicfiles.com/maskformer/panoptic-coco/maskformer_panoptic_swin_large_IN21k_384_bs64_554k/metrics.json) are 52.7. Does the metric files match the table exactly?

 
By the way, this work is nice!

**Comment by bowenc0221** [comment]
There was some bug in the post-processing code when we trained some early models, so the PQ in metric files are not consistent for those models. As the bug is not related to training, we didn't re-train those models to update the PQ numbers in the metric files. These metric files mainly serve as a reference for training losses. Please always refer to PQ numbers in the table.

**Comment by yaozhicheng** [comment]
Get it, thanks for your reply~
