### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by maelfabien** [facebookresearch/MaskFormer#3]
Hi! Thanks for open-sourcing this work.

Out of curiosity, do you have any metric on the inference time on CPU for example, and whether this kind of model could run a few times a second if quantized on a TPU for example? Thanks in advance.

**Comment by bowenc0221** [comment]
Unfortunately, we have not measured inference time on CPU or quantized version on TPU since we do not have expertise in optimizing model speed.

Since the model is built upon naive PyTorch ops, I think it should be easy to try these if you have related experience. Please let us know if you encounter any problem =)

**Comment by maelfabien** [comment]
Sure, thanks a lot for your quick reply. I’ll play around with it on my side then!
